[package]
name = "todoish"
version = "0.0.1"
edition = "2021"

[dependencies]
eframe = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ahash = { version = "0.7", features = ["serde"] }
dirs = "4.0"